/*
 * Copyright 2025 Ippon Technologies
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const afterAll: (typeof import("vitest"))["afterAll"];
  const afterEach: (typeof import("vitest"))["afterEach"];
  const assert: (typeof import("vitest"))["assert"];
  const beforeAll: (typeof import("vitest"))["beforeAll"];
  const beforeEach: (typeof import("vitest"))["beforeEach"];
  const chai: (typeof import("vitest"))["chai"];
  const describe: (typeof import("vitest"))["describe"];
  const expect: (typeof import("vitest"))["expect"];
  const it: (typeof import("vitest"))["it"];
  const suite: (typeof import("vitest"))["suite"];
  const test: (typeof import("vitest"))["test"];
  const vi: (typeof import("vitest"))["vi"];
  const vitest: (typeof import("vitest"))["vitest"];
}
